apiVersion: v1
kind: Pod
metadata:
  name: custom-agent-pod  # Eksik olan name alanını ekledik!
  labels:
    jenkins: slave
spec:
  containers:
  - name: custom-agent
    image: jenkins/inbound-agent:latest
    ports:
      - containerPort: 4040
