apiVersion: v1
kind: Pod
metadata:
  name: custom-agent-pod
spec:
  containers:
  - name: custom-agent
    image: nginx
    args:
    - /bin/sh
    - -c
    - "sleep infinity"
    ports:
      - containerPort: 4040
